/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("EmployeeServiceObjectPageObjectPage journey");

        opaTest("Navigate to EmployeeServiceObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheEmployeeServiceList.onFilterBar().iExecuteSearch();

            Then.onTheEmployeeServiceList.onTable().iCheckRows();
            When.onTheEmployeeServiceList.onTable().iPressRow(0);

            Then.onTheEmployeeServiceObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheEmployeeServiceObjectPage.iCheckSection({ section: "FieldGroup::General" });
            Then.onTheEmployeeServiceObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "EmpId" });
            Then.onTheEmployeeServiceObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "EmpName" });
            Then.onTheEmployeeServiceObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "EmpSurname" });
            Then.onTheEmployeeServiceObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "EmpDept" });
            Then.onTheEmployeeServiceObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "EmpLoc" });
            Then.onTheEmployeeServiceObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "EmpSalary" });
            Then.onTheEmployeeServiceObjectPage.onForm({ section: "FieldGroup::General" }).iCheckField({ property: "EmpRole" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});